apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-cicd
resources:
  - ../../base
images:
  - name: pod-watcher
    newName: localhost:5000/pod-watcher
    newTag: GIT_SHA
  - name: job-watcher
    newName: localhost:5000/job-watcher
    newTag: GIT_SHA
  - name: event-watcher
    newName: localhost:5000/event-watcher
    newTag: GIT_SHA
  - name: log-tailer
    newName: localhost:5000/log-tailer
    newTag: GIT_SHA
  - name: rule-engine
    newName: localhost:5000/rule-engine
    newTag: GIT_SHA
  - name: ai-supervisor
    newName: localhost:5000/ai-supervisor
    newTag: GIT_SHA
  - name: action-engine
    newName: localhost:5000/action-engine
    newTag: GIT_SHA
  - name: control-plane
    newName: localhost:5000/control-plane
    newTag: GIT_SHA
  - name: ui
    newName: localhost:5000/ui
    newTag: GIT_SHA
  - name: api-server
    newName: localhost:5000/api-server
    newTag: GIT_SHA
